### ISSUE TITLE
app_list.csv and threat_list.csv are empty

### ISSUE THREAD

**Issue by mattimustang** [PaloAltoNetworks/Splunk_TA_paloalto#14]
These lookups files are empty which cause the fields to not be added and numerous SplunkforPaloAltoNetworks app dashboards to not function. e.g. web activity.

Can you please ship a default list of apps and threats with the app again?

A side effect of this is that accelerated datamodels won't have these fields for logs they have already accelerated and will need to be rebuilt if users want to report on old logs.

cheers

Matthew

**Comment by btorresgil** [comment]
This is fixed in TA version 6.0.2.  Thanks!!
