### ISSUE TITLE
Bit decoding of flags is incorrect

### ISSUE THREAD

**Issue by acharlieh** [PaloAltoNetworks/Splunk_TA_paloalto#17]
The `EVAL-flags` seems to be doing bit decoding, however the decoding of each bit seems to be incorrect currently each segment looks like this:

    if(floor(tonumber(session_flags,16) / pow(2, <bit>))==0,null(),"flag")

The problem is, for every value above 2^\<bit\> this will return "flag", even it if the particular bit may not be set... you need to find out if the result of the division is division is even (unset) or odd (set) e.g. `% 2` to determine if the particular bit in question is set or not [as Martin Müller points out](https://answers.splunk.com/answering/236510/view.html), as a result each segment should instead look like:

    if(floor(tonumber(session_flags,16) / pow(2, <bit>))%2==0,null(),"flag")

As an example of decoding 8 bits compare the output of the current method:

    | makeresults | eval bits=8,number=mvrange(0,pow(2,bits)),bit=mvrange(0,bits) 
    | mvexpand number | mvexpand bit 
    | eval hex = tostring(number, "hex"),val=if(floor(number/pow(2, bit))==0,null(),"set") 
    | fields - number | xyseries hex,bit,val | sort 0 hex

To the output of the corrected method: 

    | makeresults | eval bits=8,number=mvrange(0,pow(2,bits)),bit=mvrange(0,bits) 
    | mvexpand number | mvexpand bit 
    | eval hex = tostring(number, "hex"),val=if(floor(number/pow(2, bit))%2==0,null(),"set") 
    | fields - number | xyseries hex,bit,val | sort 0 hex

**Comment by btorresgil** [comment]
Fixed by PaloAltoNetworks/Splunk_TA_paloalto#17.  Thanks for the PR!
