### ISSUE TITLE
Traps 4.1.1 support

### ISSUE THREAD

**Issue by JoshSchwarz** [PaloAltoNetworks/Splunk_TA_paloalto#19]
Current version of the TA supports [Traps 3.3 CEF logs](https://www.paloaltonetworks.com/documentation/33/endpoint/endpoint-admin-guide/reports-and-logging/cef-format#_13915), would like to ingest the new [CEF log format from 4+.](https://www.paloaltonetworks.com/documentation/41/endpoint/endpoint-admin-guide/reports-and-logging/forward-logs-to-an-external-logging-platform/cef-format#traps-admin-rpts-cef)

**Comment by btorresgil** [comment]
Hello, Traps 4+ CEF format is already supported. See compatibility information:

https://splunk.paloaltonetworks.com/compatibility.html#traps-advanced-endpoint-security-support

Is there a specific problem you’re running into with these Traps logs?  If so, what version of the TA are you using?

**Comment by JoshSchwarz** [comment]
PEBKAC. :P 
Misread the documentation.
