### ISSUE TITLE
minemeld feeds not populating

### ISSUE THREAD

**Issue by michaelcrandolph** [PaloAltoNetworks/Splunk_TA_paloalto#21]
I followed this guide: https://splunk.paloaltonetworks.com/autofocus-and-minemeld.html but this query "| `mm_indicators`" has no results and I do not see any connection attempts to mindmeld server (netstat -an) from Splunk.

**Comment by btorresgil** [comment]
Hello, sorry for the slow reply.  Did you ask this question on Splunk Answers?  Is it still an issue?  This area is more for bugs and feature requests, not troubleshooting.  The forum of people to help on Splunk Answers is much larger.

**Comment by btorresgil** [comment]
I'll close this for now, but feel free to comment if this is still a concern.  Thanks!
