### ISSUE TITLE
Splunk Cloud Vetting 6.1.0 (unsuccessful) - bin/input_module_minemeld_feed.py

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/Splunk_TA_paloalto#39]
Splunks Cloud Ops team have come back with an additional 'fail' for the vetting due to;

```
The app can be configured for insecure network traffic in the file bin/input_module_minemeld_feed.py, line 147, feed_url can be an insecure http url.
This issue is preventing cloud vetting from passing for the add-on
```

**Comment by simonsigre** [comment]
I am not entirely sure their assessment is accurate as at a quick look;
```
    resp = helper.send_http_request(
        url=feed_url,
        method='GET',
        parameters={'v': 'json', 'tr': 1},
        headers=feed_headers,
        verify=VERIFY_CERTIFICATE,
    )
```
I have raised this with them to see what they say

**Comment by simonsigre** [comment]
Response was;
```
I heard back from our review team, and here’s what they said: since `VERIFY_CERTIFICATE = True` can only determine whether it uses a certificate, but cannot determine the protocol, if url is set to http there will be no encryption, even the verify field is True. We tested the send_http_request function call, and if we set the url starts with 'http' and verify is 'True', the traffic goes to HTTP rather than TLSv1.2.
 
Is this a threat intelligence feed that only accepts certificate-based authentication, or is it possible to require that the URL use https and thus the communication would use TLS encryption?
 
Thanks,
App Cert Admin 
```

**Comment by simonsigre** [comment]
It appears that Splunk CloudOps have taken another look at this and have approved for deployment. I guess this could be marked as completed now?

**Comment by btorresgil** [comment]
This mod input is only used to connect with a Minemeld server. Minemeld contains threat intelligence data which can be public information. Minemeld is also often hosted internally in situations where encryption isn’t necessary or desired.

For these two reasons, there is zero risk in using http to pull the threat intelligence in many use cases. Therefore, it doesn’t make sense for the mod input to require encryption.

After discussing this directly with the certification team, they agreed and issued an exception.

Documenting this all here in case future releases hit the same certification issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by linsmeyerh** [comment]
> This mod input is only used to connect with a Minemeld server. Minemeld contains threat intelligence data which can be public information. Minemeld is also often hosted internally in situations where encryption isn’t necessary or desired.
> 
> For these two reasons, there is zero risk in using http to pull the threat intelligence in many use cases. Therefore, it doesn’t make sense for the mod input to require encryption.
> 
> After discussing this directly with the certification team, they agreed and issued an exception.
> 
> Documenting this all here in case future releases hit the same certification issue.
> 
> Sent with [GitHawk](http://githawk.com)

Can we please have this issue re-opened as of today 04/02/2019 the Palo Alto Add-on version 6.1.0 still not Cloud certified.
 
The Add-on failed Splunk Cloud certification for the following reasons:
The application can be configured for unencrypted communication, which is not permitted in Splunk Cloud. All communication must be encrypted (HTTPS preferred)., The application modifies processes that it doesn't own, which isn't permitted. Ensure all process manipulation occurs within this app.  In file bin/input_module_minemeld_feed.py  Line 147, feed_url can be an insecure http url.Once these issues are remedied you can resubmit your app for review.
