### ISSUE TITLE
Logs are not parsing as expected.

### ISSUE THREAD

**Issue by jbnsbstn** [PaloAltoNetworks/Splunk_TA_paloalto#54]
I have installed TA on my HF,Indexer and SH. Logs are not parsing as expected, I cannot see any src_ip/dst_ip etc on my fields. And my logs looks like this :

![image](https://user-images.githubusercontent.com/58504438/74704852-e0141680-5222-11ea-8d2b-427be4498f1d.png)

I got my sourcetypes segregated properly. But fields are not parsed as expected.

**Comment by paulmnguyen** [comment]
Closing this as we have determined this to not be an issue with our Add-on.
